import { makeStyles } from "@mui/styles";

const AssignmentItemStyle = makeStyles((theme: any) => ({
  // containerAll: {
  //   position: "relative",
  //   marginLeft: "60rem",
  //   width: "223px",
  //   height: "178px",
  // },
  container: {
    position: "absolute",
    width: "223px",
    height: "178px",
  },
  state: {
    float: "left",
    width: "101px",
    height: "19px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "#9D9D9E",
    textAlign: "left",
  },
  name: {
    width: "223px",
    height: "19px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "600px",
    fontSize: "17px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "#010101",
    textAlign: "center",
    // paddingTop: "10px",
    marginTop: "10px",
  },
  level: {
    float: "right",
    width: "101px",
    height: "19px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: "12px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "#AC5B4D",
    textAlign: "right",
  },

  img: {
    marginLeft: "41%",
    width: "40px",
    height: "40px",
    borderRadius: "64px",
    textAlign: "center",
    marginTop: "5px",
  },
  userName: {
    width: "223px",
    height: "16px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "##000000",
    textAlign: "center",
    marginTop: "5px",
  },
  btn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    justifyItems: "center",
    padding: "14px 32px",
    gap: "10px",
    width: "204px ",
    height: "36px",
    textAlign: "center",
    backgroundColor: "#23C686",
    marginLeft: "4%",
    marginTop: "5px",
  },
  textBtn: {
    width: "140px",
    height: "22px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "22px",
    textTransform: "capitalize",
    color: "#000000",
  },
}));
export default AssignmentItemStyle;
