import { makeStyles } from '@mui/styles'

const AssignmentItemStyle = makeStyles((theme: any) => ({
  container: {
    position: 'absolute',
    width: '223px',
    height: '178px',
  },
  state: {
    float: 'left',
    width: '101px',
    height: '19px',
    fontWeight: '700 !important',
    fontSize: `${theme.textFont.extraSmall} !important`,
    lineHeight: '19px',
    textTransform: 'capitalize',
    color: '#9D9D9E',
    textAlign: 'left',
  },
  name: {
    width: '223px',
    height: '19px',
    fontWeight: '600 !important',
    fontSize: `${theme.textFont.small} !important`,
    lineHeight: '19px !important',
    textTransform: 'capitalize',
    color: '#010101',
    textAlign: 'center',
    marginTop: '10px  !important',
  },
  level: {
    float: 'right',
    width: '101px',
    height: '19px',

    fontWeight: '700 !important',
    fontSize: `${theme.textFont.extraSmall} !important`,
    lineHeight: '19px !important',
    textTransform: 'capitalize',
    color: '#AC5B4D',
    textAlign: 'right',
  },

  img: {
    marginLeft: '41%',
    marginTop: '10px !important',
  },
  userName: {
    width: '223px',
    height: '16px',
    fontStyle: 'normal',
    fontWeight: '700 !important',
    fontSize: `${theme.textFont.small} !important`,
    lineHeight: '19px',
    textTransform: 'capitalize',
    color: '##000000',
    textAlign: 'center',
    // marginTop: "5px !important",
  },
  btn: {
    padding: '14px 32px !important',
    gap: '10px !important',
    width: '204px',
    height: '36px ',
    backgroundColor: ` ${theme.color.btnGreenColor} !important`,
    marginLeft: '4% !important',
    marginTop: '5px !important',
  },
  textBtn: {
    width: '140px',
    height: '22px',
    fontStyle: 'normal !important',
    fontWeight: '600 !important',
    fontSize: `${theme.textFont.small} !important`,
    lineHeight: '22px !important',
    textTransform: 'capitalize',
    color: '#000000 !important',
  },
}))
export default AssignmentItemStyle
