import { makeStyles } from "@mui/styles";

const MyAssignmentItemStyle = makeStyles((theme: any) => ({
  paperWrap: {
    width: "31rem",
    height: "3.53rem",
    border: "1px solid black",
    padding: "10px",
  },
  name: {
    float: "left",
    width: "208px",
    height: "36px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "600px",
    fontSize: "17px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "#010101",
    textAlign: "center",
    // paddingTop: "10px",
    paddingTop: "6px",
  },
  level: {
    float: "left",
    width: "90px",
    height: "36px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: "12px",
    lineHeight: "19px",
    textTransform: "capitalize",
    color: "#AC5B4D",
    textAlign: "center",
    paddingTop: "6px",
  },
  btn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    justifyItems: "center",
    padding: "14px 32px",
    gap: "10px",
    width: "170px ",
    height: "36px",
    textAlign: "center",
    backgroundColor: "#23C686",
    marginLeft: "4%",
    marginTop: "5px",
  },
  textBtn: {
    width: "140px",
    height: "22px",
    fontFamily: "Arial",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "16px",
    lineHeight: "22px",
    textTransform: "capitalize",
    color: "#000000",
  },
}));

export default MyAssignmentItemStyle;
